[context.rama_1.environment]
  MY_APP_VERSION = "wololoooooooooooooocontext"

[dev.environment]
  MY_APP_VERSION = "wololoooooooooooooodev"

[build]
  MY_APP_VERSION = "wololoooooooooooooobuild"

[[plugins]]
  package = "netlify-plugin-bundle-env"